### ISSUE TITLE
Help with handelling <InterruptedException> in CertificateTransparencyBase class

### ISSUE THREAD

**Issue by dsatija** [appmattus/certificatetransparency#119]
Hi @mattmook , we are facing the same issue as https://github.com/appmattus/certificatetransparency/issues/48. 
Getting this error :
**Unable to load log servers with log-list.zip failed to load with kotlinx.coroutines.JobCancellationException**
Here's the error :
`E/CertificateTransparencyManager: Certificate transparency failed for host : y.x.com with result: Failure: Unable to load log servers with log-list.zip failed to load with kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=BlockingCoroutine{Cancelled}@5bb23e7 Caused by: java.lang.InterruptedException at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:159) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:3) at com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyBase.hasValidSignedCertificateTimestamp(CertificateTransparencyBase.kt:7) at com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyBase.verifyCertificateTransparency(CertificateTransparencyBase.kt:77) at`

Could you suggest what can be done here ? We need to handle it in some way since its causing our crashlytics blow up . Thankyou for your work ! 

_Originally posted by @dsatija in https://github.com/appmattus/certificatetransparency/issues/48#issuecomment-2221504788_

**Comment by dsatija** [comment]
@mattmook this is a blocker for us for rolling this feature out. Will appreciate any pointers you have. Thanks!

**Comment by UmerTaptap** [comment]
hi, how to stop a request if we get SCT not enable status?
