### ISSUE TITLE
NullPointerException in LogListJsonParserV2.parseJson

### ISSUE THREAD

**Issue by mattmook** [appmattus/certificatetransparency#16]
Raised by @ikeed and moved from https://github.com/babylonhealth/certificate-transparency-android/issues/69

Our Android users are having an intermittent issue with the following stack trace:

We're using v0.3.0 of your lib.  Please let me know what other info would be of interest to you.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
       at java.util.HashMap.hash(HashMap.java:338)
       at java.util.HashMap.containsKey(HashMap.java:595)
       at java.util.HashSet.contains(HashSet.java:203)
       at com.google.gson.internal.$Gson$Types.resolve(.java:346)
       at com.google.gson.internal.$Gson$Types.resolve(.java:381)
       at com.google.gson.internal.$Gson$Types.resolve(.java:337)
       at com.google.gson.internal.$Gson$Types.getSupertype(.java:283)
       at com.google.gson.internal.$Gson$Types.getCollectionElementType(.java:302)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.Gson.fromJson(Gson.java:926)
       at com.google.gson.Gson.fromJson(Gson.java:892)
       at com.google.gson.Gson.fromJson(Gson.java:841)
       at com.google.gson.Gson.fromJson(Gson.java:813)
       at com.babylon.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.parseJson(LogListJsonParserV2.java:36)
       at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transformSuccess(RawLogListToLogListResultTransformer.java:51)
       at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transform(RawLogListToLogListResultTransformer.java:35)
       at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory.java:49)
       at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory.java:29)
       at com.babylon.certificatetransparency.datasource.DataSource$oneWayTransform$1.get(DataSource.java:113)
       at com.babylon.certificatetransparency.datasource.DataSource$oneWayTransform$1$get$1.invokeSuspend(DataSource.java:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:241)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.java:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:740)`

I suspect this is an issue on our end but any help you can provide would be greatly appreciated.

**Comment by mattmook** [comment]
I've been unable to reproduce this although I do note the same stack trace from Gson, google/gson#1778, so the bug may sit outside the library.

I still want to look for a work around so any additional data you have such as devices affected, OS version etc would be most useful.

**Comment by ajinabraham** [comment]
Hi @mattmook,
I am also seeing these exceptions for some of our users. 
Using `com.appmattus.certificatetransparency:certificatetransparency-android:0.3.0`

Usage:
```
val CT = CTInterceptorBuilder()
    .setFailOnError(true)
    .includeHost("*.*")
    .build()
return OkHttpClient.Builder()
    .....
    .addNetworkInterceptor(CT)
    .build()
```
Stack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
        at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.containsKey(HashMap.java:595)
        at java.util.HashSet.contains(HashSet.java:203)
        at com.google.gson.internal.$Gson$Types.resolve(unknown:346)
        at com.google.gson.internal.$Gson$Types.resolve(unknown:381)
        at com.google.gson.internal.$Gson$Types.resolve(unknown:337)
        at com.google.gson.internal.$Gson$Types.getSupertype(unknown:283)
        at com.google.gson.internal.$Gson$Types.getCollectionElementType(unknown:302)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory:52)
        at com.google.gson.Gson.getAdapter(Gson:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory:102)
        at com.google.gson.Gson.getAdapter(Gson:458)
        at com.google.gson.Gson.fromJson(Gson:931)
        at com.google.gson.Gson.fromJson(Gson:897)
        at com.google.gson.Gson.fromJson(Gson:846)
        at com.google.gson.Gson.fromJson(Gson:817)
        at com.babylon.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.parseJson(LogListJsonParserV2:36)
        at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transformSuccess(RawLogListToLogListResultTransformer:51)
        at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transform(RawLogListToLogListResultTransformer:35)
        at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory:49)
        at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory:29)
        at com.babylon.certificatetransparency.datasource.DataSource$oneWayTransform$1.get(DataSource:113)
        at com.babylon.certificatetransparency.datasource.DataSource$oneWayTransform$1$get$1.invokeSuspend(Unknown:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask:106)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler:665)
```

### More information

* The exception is not recurring, it happens once per user.
* Happened on Android versions: `10, 9, 8.1`
* Devices: `LG, Samsung, Motorola`

**Comment by EmMper** [comment]
I got same problem, anyone has solutions?

**Comment by mattmook** [comment]
The next release of the library will move to kotlinx serialization so this exception will not occur again (although no doubt could introduce a different exception instead, just hopefully one with an easier to deal with stack trace)
