### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException: ...com.babylon.certificatetransparency.internal.loglist.model.v2.Operator

### ISSUE THREAD

**Issue by gilbertparreno** [appmattus/certificatetransparency#20]
I have no idea why this issue only occurs on Samsung's J7 Prime Android 8:

`Fatal Exception: java.lang.ClassCastException: i.l.e.w.g cannot be cast to com.babylon.certificatetransparency.internal.loglist.model.v2.Operator
       at com.babylon.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.buildLogServerList(LogListJsonParserV2.java:74)
       at com.babylon.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.parseJson(LogListJsonParserV2.java:41)
       at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transformSuccess(RawLogListToLogListResultTransformer.java:51)
       at com.babylon.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.transform(RawLogListToLogListResultTransformer.java:35)
       at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory.java:49)
       at com.babylon.certificatetransparency.internal.loglist.LogListDataSourceFactory$create$2.invoke(LogListDataSourceFactory.java:29)
       at com.babylon.certificatetransparency.datasource.DataSource$oneWayTransform$1.get(DataSource.java:113)
       at com.babylon.certificatetransparency.datasource.DataSource$oneWayTransform$1$get$1.invokeSuspend(DataSource.java:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)`

**Comment by mattmook** [comment]
I don't suppose with this exception you're able to deobfuscate `i.l.e.w.g` so we've got more of an idea about what its trying to cast?

**Comment by mattmook** [comment]
The latest release v1.0.0 changes the parser used so I'm going to close this issue for now. If you see the same issue under the latest release please feel free to re-create.
