### ISSUE TITLE
Getting NoClassDefFoundError

### ISSUE THREAD

**Issue by AndroidDev08** [appmattus/certificatetransparency#40]
Hi,

I added the certificate transparency logger to my project and I am getting the below crash for NoClassDefFoundError.

implementation 'com.appmattus.certificatetransparency:certificatetransparency-android:1.1.0'

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bouncycastle/tls/TlsUtils;
        at com.appmattus.certificatetransparency.internal.utils.X509CertificateExtKt.parseSctsFromCertExtension(X509CertificateExt.kt:52)
        at com.appmattus.certificatetransparency.internal.utils.X509CertificateExtKt.signedCertificateTimestamps(X509CertificateExt.kt:43)
        at com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyBase.hasValidSignedCertificateTimestamp(CertificateTransparencyBase.kt:127)
        at com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyBase.verifyCertificateTransparency(CertificateTransparencyBase.kt:95)
        at com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor.intercept(CertificateTransparencyInterceptor.kt:69)

Thanks
Ankit

**Comment by mattmook** [comment]
This looks likely to be a conflict with the version of bouncycastle being resolved by your project. Some of these classes moved from version 1.6x to 1.7x which we currently use.

It would be worth running  `./gradlew app:dependencies` and seeing what versions were resolved
